[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Biến API chính cho hệ thống UmiJS v4
  UMI_APP_API_URL = "https://ript1307-01-2026-nhom11-kthp.onrender.com"
  
  # Giữ thêm biến này để phòng hờ các file cũ (Legacy) như Register hay Progress dùng
  REACT_APP_API_URL = "https://ript1307-01-2026-nhom11-kthp.onrender.com"
